all: UdpServer.class UdpClient.class TcpServer.class TcpClient.class

UdpClient.class: UdpClient.java
	javac UdpClient.java

UdpServer.class: UdpServer.java
	javac UdpServer.java

TcpClient.class: TcpClient.java
	javac TcpClient.java

TcpServer.class: TcpServer.java
	javac TcpServer.java

clean:
	rm *.class